services:
  oracle-db:
    image: container-registry.oracle.com/database/free:23.7.0.0-lite-amd64
    container_name: customerflow-db
    ports:
      - "${DB_PORT:-1521}:1521"
    environment:
      ORACLE_PWD: "${DB_PASSWORD:-changeme}"
      ORACLE_CHARACTERSET: "${DB_CHARACTERSET:-AL32UTF8}"
      ORACLE_PDB: "${DB_PDB:-customerflowpdb}"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./setup-sql:/opt/oracle/scripts/startup

  app:
    build: .
    container_name: customerflow-api
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      DB_HOST: oracle-db
      DB_PORT: "${DB_PORT}"
      DB_PDB: "${DB_PDB}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_EXPIRATION: "${JWT_EXPIRATION}"
      JPA_DDL_AUTO: "${JPA_DDL_AUTO:-}"
      JPA_SHOW_SQL: "${JPA_SHOW_SQL:-}"
      JPA_FORMAT_SQL: "${JPA_FORMAT_SQL:-}"
      API_DOCS_ENABLED: "${API_DOCS_ENABLED:-}"
      SWAGGER_UI_ENABLED: "${SWAGGER_UI_ENABLED:-}"
      INITIAL_ADMIN_EMAIL: "${INITIAL_ADMIN_EMAIL:-}"
      INITIAL_ADMIN_PASSWORD: "${INITIAL_ADMIN_PASSWORD:-}"
    restart: always
    depends_on:
      oracle-db:
        condition: service_healthy

volumes:
  oracle-data:
