spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/customerflowpdb
    username: CUSTOMERFLOW_DEV
    password: changeme
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true