server:
  port: 8080

api:
  url: ${API_URL}

spring:
  application:
    name: customerflow-api
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}/${DB_PDB:customerflowpdb}
    username: ${DB_USERNAME:CUSTOMERFLOW_DEV}
    password: ${DB_PASSWORD:changeme}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: ${JPA_FORMAT_SQL:false}
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:B9KcRasDYfFpDKYavK70qUYukxKGJXLfTXaGrQuoGdc}
      expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

initial-setup:
  admin:
    email: ${INITIAL_ADMIN_EMAIL:admin@example.com}
    password: ${INITIAL_ADMIN_PASSWORD:changeme}