server:
  port: 8080

spring:
  application:
    name: customerflow
  jpa:
    hibernate:
      ddl-auto: update # "create-drop", "update" or "none" tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource: # Oracle settings
    url: jdbc:oracle:thin:@//localhost:1521/customerflowpdb
    username: CUSTOMERFLOW_DEV
    password: changeme
    driver-class-name: oracle.jdbc.OracleDriver
