-- First connect to PDB
ALTER SESSION SET CONTAINER = customerflowpdb;

-- Create User
CREATE USER CUSTOMERFLOW_DEV IDENTIFIED BY "changeme";
GRANT CONNECT, RESOURCE TO CUSTOMERFLOW_DEV;
GRANT CREATE SESSION TO CUSTOMERFLOW_DEV;
GRANT UNLIMITED TABLESPACE TO CUSTOMERFLOW_DEV;

exit;